//= require 'constants'

//= require 'lib/helpers'
//= require 'lib/shims'
//= require 'lib/scene_manager'
//= require 'lib/scene'
//= require 'lib/loader'
//= require 'lib/input'
//= require 'lib/physics'
//= require 'lib/world'
//= require 'lib/sprite'
//= require 'lib/button'

//= require 'globals'
//= require 'stretchy_sprite'
//= require 'slime'
//= require 'box'
//= require 'ball'
//= require 'ai'
//= require 'scoreboard'

//= require 'scenes/loading_scene'
//= require 'scenes/menu_scene'
//= require 'scenes/slime_volleyball'

//= require 'main'