//= require '../shared/lib/shims'
//= require '../shared/constants'

//= require '../shared/lib/helpers'
//= require '../shared/lib/scene_manager'
//= require '../shared/lib/scene'
//= require '../shared/lib/loader'
//= require '../shared/lib/input'
//= require '../shared/lib/sprite'
//= require '../shared/lib/button'
//= require '../shared/lib/gamepad'

//= require '../shared/globals'
//= require 'stretchy_sprite'
//= require '../shared/ball'
//= require '../shared/slime'
//= require 'scoreboard'
//= require '../shared/world'

//= require 'scenes/loading_scene'
//= require 'scenes/menu_scene'
//= require 'scenes/slime_volleyball'
//= require '../shared/input_snapshot'
//= require 'scenes/network_slime_volleyball'
//= require 'scenes/instructions_scene'
//= require 'scenes/options_scene'

//= require 'main'