//= require 'lib/shims'
//= require 'constants'

//= require 'lib/helpers'
//= require 'lib/scene_manager'
//= require 'lib/scene'
//= require 'lib/loader'
//= require 'lib/input'
//= require 'lib/sprite'
//= require 'lib/button'
//= require 'lib/gamepad'

//= require 'globals'
//= require 'stretchy_sprite'
//= require 'ball'
//= require 'slime'
//= require 'scoreboard'
//= require 'world'

//= require 'scenes/loading_scene'
//= require 'scenes/menu_scene'
//= require 'scenes/slime_volleyball'
//= require 'scenes/network_slime_volleyball'
//= require 'scenes/instructions_scene'
//= require 'scenes/options_scene'

//= require 'main'